### ISSUE TITLE
color palette: asexual flag

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#167]
# Description
source: [flagcolorcodes: Asexual Flag Color Codes](https://www.flagcolorcodes.com/asexual)

# Tasks
- [x] `#000000`
- [x] `#A3A3A3`
- [x] `#FFFFFF`
- [x] `#800080`
- [x] palette implementation

**Comment by azurepolarbear** [comment]
This item is staged. Development is complete. Closes #167
