### ISSUE TITLE
Feature Request - 2024-04-25 - Add Random Function to Choose a Random Element and Remove it From the Given List

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#59]
# Description

Add a new function to the Random class to choose a random element from a list or weighted list, remove the element, and return the altered list.

# Tasks

- [x] implement new function
  - [x] regular list
  - [x] ~weighted list~
- [x] unit tests

**Comment by blwatkins** [comment]
Issue is ready to close after next merge of 53-move-full-library-into-main-repository.

**Comment by azurepolarbear** [comment]
closing issue to mark as complete.  Code changes are in branch 53-move-full-library-into-main-repository
