### ISSUE TITLE
Feature Request - 2024-04-28 -  Output Library as ES Modules with Single Types File

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library#65]
# Description

We want to output the library as ES Modules to enable tree shaking in rollup, while still having a single `.d.ts` file for npm TypeScript types.

# Tasks

**Comment by blwatkins** [comment]
Issue is ready to close after next merge of 53-move-full-library-into-main-repository.

**Comment by azurepolarbear** [comment]
closing issue so we don't think it's not done.

completed code is in branch 53-move-full-library-into-main-repository.
